### ISSUE TITLE
EDF will not run at slow speed during staging

### ISSUE THREAD

**Issue by tboy555** [NegativeC/ducted-fan-pinewood-derby#1]
Hey Christian, I hope you get this, love the code and am planning on using it next week. I have it loaded into my trinket and working fine except for the staging speed.  Nothing happens there but the light turns on.  EDF runs to full power when the switch is released.  I tried a regular servo and got movement on it for two different positions.  

Im guessing it is a calibration issue?  Any ideas?

**Comment by NegativeC** [comment]
I think if you increase the STAGEDSPEED = 50 or so it’ll spin.  Also, you may need to read about your ESC on how to set the full throttle position.  Once it learns the max, it generates a linear curve from 0 to 100%.

**Comment by tboy555** [comment]
Hey thanks for the reply. Really enjoying your code!  I’m not a programmer and so thanks to your help I’m able to do this!!

I think you are right, but late last night I tried another wax I had on hand rated for much less power. It worked as written!  I figure that I’ll be ok with races only being 2 seconds or less!  

I will mess with the bigger speed control when I have more time. For now I’ll use the smaller one. 

I think I will upload my edf mount to thingiverse once done, maybe it will help others. 

Troy

**Comment by NegativeC** [comment]
Cool, would like to see your mount.
